### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [oxozle/OXPatternLock#3]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks information.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to do it.

What are your thoughts?

**Comment by lfarah** [comment]
Biggest problem is a better implementation section

**Comment by lfarah** [comment]
Please fix that before I can [merge this](https://github.com/vsouza/awesome-ios/pull/1406)

**Comment by oxozle** [comment]
Thank you for review. Just to understand. Do you mean library implementation section or usage section?

**Comment by lfarah** [comment]
@oxozle Usage

**Comment by lfarah** [comment]
Please [take a look at this](https://github.com/awesome-labs/LFTimePicker#usage-example)

**Comment by oxozle** [comment]
Updated from example
